# HW 1

## Question 1

Suppose our input data to a map-reduce operation consists of integer values (the keys are not important). The map function takes an integer i and produces the list of pairs $(p,i)$ such that $p$ is a prime divisor of $i$. For example, $map(12) = [(2,12),(3,12)]$. The reduce function is addition. That is, $reduce(p,[i_1,i_2,...,i_k])$ is $(p,i_1+i_2+...+i_k)$.

Compute the output, if the input is the set of integers $15, 21, 24, 30, 49$. Then, identify, in the list below, one of the pairs in the output.

**Solution:**

In [11]:
from itertools import groupby

# first 25 primes
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73]
targets = [15,21,24,30,49]

def map_func(n):
    divisors = filter(lambda x: n % x == 0, primes)
    return [(d, n) for d in divisors]

def reduce_func(kv_pairs): 
    return sum(v for k, v in kv_pairs)

res = []
    
for n in targets:
    res += map_func(n)
    
res = sorted(res, key=lambda c: c[0])
    
for key, group in groupby(res, lambda c: c[0]):
    print("key=%s, res=%s" % (key, reduce_func(group)))

key=2, res=54
key=3, res=90
key=5, res=45
key=7, res=70


## Question 2
Consider three Web pages with the following links: $[(A,B), (A,C), (B,C), (C,C)]$. 

Suppose we compute PageRank with a β of 0.7, and we introduce the additional constraint that the sum of the PageRanks of the three pages must be 3, to handle the problem that otherwise any multiple of a solution will also be a solution. Compute the PageRanks a, b, and c of the three pages A, B, and C, respectively. Then, identify from the list below, the true statement.

**Solution**

Matrix A will have the following form:
$$
0.7 *
\begin{Bmatrix}
 0 & 0 & 0\\
 \frac{1}{2} & 0 & 0\\
 \frac{1}{2} & 1 & 1
\end{Bmatrix}
+ 
0.3 *
\begin{Bmatrix}
 \frac{1}{3} & \frac{1}{3} & \frac{1}{3}\\
 \frac{1}{3} & \frac{1}{3} & \frac{1}{3}\\
 \frac{1}{3} & \frac{1}{3} & \frac{1}{3}
\end{Bmatrix}
$$
Additional constraint: $r_a + r_b + r_c = 3$


In [22]:
import numpy as np
from scipy import linalg

m1 = np.matrix([
    [0, 0, 0],
    [.5, 0, 0],
    [.5, 1, 1]
])

m2 = np.matrix([
    [1/3, 1/3, 1/3],
    [1/3, 1/3, 1/3],
    [1/3, 1/3, 1/3]
])

m3 = np.matrix([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, -1]
])

m4 = 0.7 * m1 + 0.3 * m2 + m3

m5 = np.vstack((m4, [1, 1, 1]))
m5

matrix([[-0.9 ,  0.1 ,  0.1 ],
        [ 0.45, -0.9 ,  0.1 ],
        [ 0.45,  0.8 , -0.2 ],
        [ 1.  ,  1.  ,  1.  ]])

Solving with Wolfram gives $a=0.3, b=0.405, c=2.295$

## Question 3


Graph: $[(A, B), (B, C), (A, C), (C, A)]$. Suppose we compute PageRank with β=0.85. Write the equations for the PageRanks a, b, and c of the three pages A, B, and C, respectively. Then, identify in the list below, one of the equations.

**Solution**

In [23]:
m1 = np.matrix([
    [0, 0, 1],
    [.5, 0, 0],
    [.5, 1, 0]
])

m2 = np.matrix([
    [1/3, 1/3, 1/3],
    [1/3, 1/3, 1/3],
    [1/3, 1/3, 1/3]
])

m3 = np.matrix([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, -1]
])

m4 = 0.85 * m1 + 0.15 * m2 + m3

m5 = np.vstack((m4, [1, 1, 1]))
m5

matrix([[-0.95 ,  0.05 ,  0.9  ],
        [ 0.475, -0.95 ,  0.05 ],
        [ 0.475,  0.9  , -0.95 ],
        [ 1.   ,  1.   ,  1.   ]])

## Question 4

Assuming no "taxation," compute the PageRanks a, b, and c of the three pages A, B, and C, using iteration, starting with the "0th" iteration where all three pages have rank a = b = c = 1. Compute as far as the 5th iteration, and also determine what the PageRanks are in the limit. Then, identify the true statement from the list below

In [27]:
r5 = m1**5 * np.array([[1], [1], [1]])
r5

matrix([[1.25 ],
        [0.625],
        [1.125]])