# HW 13

## Question 2

In [39]:
import numpy as np

h = np.array([1, 1])
L = np.matrix([[1, 1], [0, 1]])

for i in range(1000):
    a = L.T.dot(h)
    a = a / a.max()
    a = a.reshape(2, 1)
    h = L.dot(a)
    h = h / h.max()
    h = h.reshape(2, 1)

h[1] / h[0]

matrix([[0.61803399]])

## Question 3

In [55]:
h = np.array([1, 1, 1, 1])
L = np.matrix([
    [0, 1, 1, 0], 
    [1, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

for i in range(2):
    a = L.T.dot(h)
    a = a / a.max()
    a = a.reshape(4, 1)
    h = L.dot(a)
    h = h / h.max()
    h = h.reshape(4, 1)
    
h, a

(matrix([[1.   ],
         [0.125],
         [0.125],
         [0.625]]),
 matrix([[0.2],
         [0.6],
         [1. ],
         [0.2]]))